#pragma once
// Auto-generated by tools/convert_swsh_nests.py — do not edit manually
#include <cstdint>

namespace SwShDenLocations {

struct DenLocation {
    int mapX, mapY;
    uint8_t locationId;
};

inline constexpr int DEN_COUNT = 276;

inline constexpr DenLocation DEN_LOCATIONS[276] = {
    {  185,   977, 12}, // Den   0 (WA)
    {  125,  1005, 12}, // Den   1 (WA)
    {  114,   936, 12}, // Den   2 (WA)
    {  311,   998, 12}, // Den   3 (WA)
    {  233,   948, 12}, // Den   4 (WA)
    {  337,   996, 12}, // Den   5 (WA)
    {  209,   976, 12}, // Den   6 (WA)
    {  136,   906, 12}, // Den   7 (WA)
    {  252,   905, 12}, // Den   8 (WA)
    {   30,   927,  2}, // Den   9 (WA)
    {   12,   851,  2}, // Den  10 (WA)
    {   12,   861,  2}, // Den  11 (WA)
    {   20,   913,  2}, // Den  12 (WA)
    {   40,   878,  2}, // Den  13 (WA)
    {   52,   776, 15}, // Den  14 (WA)
    {   68,   652, 15}, // Den  15 (WA)
    {   50,   700, 15}, // Den  16 (WA)
    {  217,   913,  4}, // Den  17 (WA)
    {  158,   705,  4}, // Den  18 (WA)
    {  220,   759,  4}, // Den  19 (WA)
    {  248,   852,  4}, // Den  20 (WA)
    {  129,   818, 16}, // Den  21 (WA)
    {  131,   735, 16}, // Den  22 (WA)
    {  105,   907, 16}, // Den  23 (WA)
    {   50,   909, 16}, // Den  24 (WA)
    {   98,   750, 16}, // Den  25 (WA)
    {  107,   652, 16}, // Den  26 (WA)
    {  186,   816,  0}, // Den  27 (WA)
    {  310,   824, 13}, // Den  28 (WA)
    {  359,   980, 13}, // Den  29 (WA)
    {  393,   962, 13}, // Den  30 (WA)
    {  328,   761, 13}, // Den  31 (WA)
    {  352,   765, 13}, // Den  32 (WA)
    {  443,   895,  7}, // Den  33 (WA)
    {  388,   817,  7}, // Den  34 (WA)
    {  443,   830,  7}, // Den  35 (WA)
    {  410,   952,  7}, // Den  36 (WA)
    {  447,   815,  7}, // Den  37 (WA)
    {  393,   781, 11}, // Den  38 (WA)
    {  314,   755, 11}, // Den  39 (WA)
    {  440,   658, 11}, // Den  40 (WA)
    {  281,   717, 11}, // Den  41 (WA)
    {  440,   703, 11}, // Den  42 (WA)
    {  310,   654,  4}, // Den  43 (WA)
    {  443,   792, 11}, // Den  44 (WA)
    {  412,   533, 10}, // Den  45 (WA)
    {  345,   537, 10}, // Den  46 (WA)
    {  365,   559, 10}, // Den  47 (WA)
    {  408,   570, 10}, // Den  48 (WA)
    {  193,   295,  1}, // Den  49 (WA)
    {  274,   321,  1}, // Den  50 (WA)
    {  328,   330,  1}, // Den  51 (WA)
    {  370,   452,  1}, // Den  52 (WA)
    {  224,   282,  1}, // Den  53 (WA)
    {  342,   312,  1}, // Den  54 (WA)
    {  340,   269,  1}, // Den  55 (WA)
    {  305,   323,  1}, // Den  56 (WA)
    {  334,   368,  1}, // Den  57 (WA)
    {  343,   222, 14}, // Den  58 (WA)
    {  348,   195, 14}, // Den  59 (WA)
    {  200,   244, 14}, // Den  60 (WA)
    {  305,   183, 14}, // Den  61 (WA)
    {  348,   180, 14}, // Den  62 (WA)
    {  260,   199, 14}, // Den  63 (WA)
    {  211,   205, 14}, // Den  64 (WA)
    {  303,   242, 14}, // Den  65 (WA)
    {  324,   209, 14}, // Den  66 (WA)
    {  326,   219, 14}, // Den  67 (WA)
    {  330,   215, 14}, // Den  68 (WA)
    {  282,   195, 14}, // Den  69 (WA)
    {  265,   139,  3}, // Den  70 (WA)
    {  307,    93,  3}, // Den  71 (WA)
    {  331,    84,  3}, // Den  72 (WA)
    {  219,    99,  3}, // Den  73 (WA)
    {  243,   120,  3}, // Den  74 (WA)
    {  262,   174,  3}, // Den  75 (WA)
    {  283,    98,  3}, // Den  76 (WA)
    {  304,   112,  3}, // Den  77 (WA)
    {  306,   145,  6}, // Den  78 (WA)
    {  214,   168,  3}, // Den  79 (WA)
    {  334,   145,  6}, // Den  80 (WA)
    {  347,   103,  6}, // Den  81 (WA)
    {  363,    88,  6}, // Den  82 (WA)
    {  338,   122,  6}, // Den  83 (WA)
    {  339,    35,  8}, // Den  84 (WA)
    {  310,    65,  8}, // Den  85 (WA)
    {  202,    34,  8}, // Den  86 (WA)
    {  237,    67,  8}, // Den  87 (WA)
    {  183,    47,  8}, // Den  88 (WA)
    {  221,    50,  8}, // Den  89 (WA)
    {  354,    60,  8}, // Den  90 (WA)
    {  181,   185,  5}, // Den  91 (WA)
    {  199,   145,  5}, // Den  92 (WA)
    {  193,   173,  5}, // Den  93 (WA)
    {  202,    95,  5}, // Den  94 (WA)
    {  185,   135,  5}, // Den  95 (WA)
    {  170,    35,  9}, // Den  96 (WA)
    {  128,    58,  9}, // Den  97 (WA)
    {  161,    80,  9}, // Den  98 (WA)
    {  143,    39,  9}, // Den  99 (WA)
    {  643,   822, 17}, // Den 100 (IoA)
    {  770,   794, 17}, // Den 101 (IoA)
    {  723,   812, 17}, // Den 102 (IoA)
    {  862,   770, 17}, // Den 103 (IoA)
    {  673,   766, 17}, // Den 104 (IoA)
    {  882,   745, 17}, // Den 105 (IoA)
    {  661,   838, 17}, // Den 106 (IoA)
    {  683,   792, 17}, // Den 107 (IoA)
    {  831,   770, 17}, // Den 108 (IoA)
    {  727,   779, 17}, // Den 109 (IoA)
    {  662,   681, 18}, // Den 110 (IoA)
    {  741,   680, 18}, // Den 111 (IoA)
    {  697,   645, 18}, // Den 112 (IoA)
    {  732,   631, 18}, // Den 113 (IoA)
    {  634,   623, 18}, // Den 114 (IoA)
    {  603,   591, 18}, // Den 115 (IoA)
    {  667,   614, 18}, // Den 116 (IoA)
    {  609,   668, 18}, // Den 117 (IoA)
    {  554,   577, 18}, // Den 118 (IoA)
    {  533,   524, 19}, // Den 119 (IoA)
    {  687,   535, 19}, // Den 120 (IoA)
    {  622,   521, 19}, // Den 121 (IoA)
    {  578,   512, 19}, // Den 122 (IoA)
    {  636,   492, 19}, // Den 123 (IoA)
    {  553,   529, 19}, // Den 124 (IoA)
    {  488,   480, 20}, // Den 125 (IoA)
    {  483,   556, 20}, // Den 126 (IoA)
    {  465,   605, 20}, // Den 127 (IoA)
    {  446,   649, 20}, // Den 128 (IoA)
    {  453,   561, 20}, // Den 129 (IoA)
    {  320,   526, 20}, // Den 130 (IoA)
    {  442,   609, 20}, // Den 131 (IoA)
    {  412,   566, 20}, // Den 132 (IoA)
    {  947,   506, 21}, // Den 133 (IoA)
    {  912,   467, 22}, // Den 134 (IoA)
    {  925,   433, 22}, // Den 135 (IoA)
    {  913,   408, 22}, // Den 136 (IoA)
    {  895,   365, 22}, // Den 137 (IoA)
    {  526,   650, 23}, // Den 138 (IoA)
    {  576,   714, 23}, // Den 139 (IoA)
    {  565,   726, 23}, // Den 140 (IoA)
    {  586,   726, 23}, // Den 141 (IoA)
    {  621,   749, 23}, // Den 142 (IoA)
    {  528,   695, 23}, // Den 143 (IoA)
    {  408,   809, 24}, // Den 144 (IoA)
    {  426,   790, 24}, // Den 145 (IoA)
    {  360,   850, 24}, // Den 146 (IoA)
    {  327,   787, 24}, // Den 147 (IoA)
    {  707,   421, 25}, // Den 148 (IoA)
    {  832,   398, 25}, // Den 149 (IoA)
    {  591,   430, 25}, // Den 150 (IoA)
    {  666,   334, 25}, // Den 151 (IoA)
    {  758,   338, 25}, // Den 152 (IoA)
    {  719,   377, 25}, // Den 153 (IoA)
    {  659,   397, 25}, // Den 154 (IoA)
    {  665,   243, 26}, // Den 155 (IoA)
    {  784,   212, 26}, // Den 156 (IoA)
    {  881,   235, 26}, // Den 157 (IoA)
    {  321,  1004, 27}, // Den 158 (IoA)
    {  782,   962, 27}, // Den 159 (IoA)
    { 1040,   752, 27}, // Den 160 (IoA)
    {  970,   701, 27}, // Den 161 (IoA)
    {  759,  1015, 27}, // Den 162 (IoA)
    {  558,  1082, 27}, // Den 163 (IoA)
    {  523,   993, 27}, // Den 164 (IoA)
    {  129,   797, 28}, // Den 165 (IoA)
    {   75,   658, 28}, // Den 166 (IoA)
    {  120,   523, 28}, // Den 167 (IoA)
    {  120,   547, 28}, // Den 168 (IoA)
    {  287,   559, 28}, // Den 169 (IoA)
    {  258,   654, 28}, // Den 170 (IoA)
    {  174,   852, 28}, // Den 171 (IoA)
    {  162,   808, 28}, // Den 172 (IoA)
    {  162,   763, 28}, // Den 173 (IoA)
    {  299,   356, 29}, // Den 174 (IoA)
    {  214,   349, 29}, // Den 175 (IoA)
    {  185,   302, 29}, // Den 176 (IoA)
    {  247,   298, 29}, // Den 177 (IoA)
    {  271,   273, 29}, // Den 178 (IoA)
    {  468,   451, 30}, // Den 179 (IoA)
    {  605,   166, 30}, // Den 180 (IoA)
    {  672,   120, 30}, // Den 181 (IoA)
    {  716,    91, 30}, // Den 182 (IoA)
    {  597,   105, 30}, // Den 183 (IoA)
    {  471,   152, 31}, // Den 184 (IoA)
    {  490,   194, 31}, // Den 185 (IoA)
    {  464,   237, 31}, // Den 186 (IoA)
    {  413,   237, 31}, // Den 187 (IoA)
    {  386,   195, 31}, // Den 188 (IoA)
    {  414,   148, 31}, // Den 189 (IoA)
    {  455,   710, 32}, // Den 190 (CT)
    {  571,   697, 32}, // Den 191 (CT)
    {  550,   705, 32}, // Den 192 (CT)
    {  654,   775, 32}, // Den 193 (CT)
    {  699,   765, 32}, // Den 194 (CT)
    {  624,   737, 32}, // Den 195 (CT)
    {  431,   903, 33}, // Den 196 (CT)
    {  458,   887, 33}, // Den 197 (CT)
    {  514,   925, 33}, // Den 198 (CT)
    {  461,   925, 33}, // Den 199 (CT)
    {  598,   936, 33}, // Den 200 (CT)
    {  443,  1088, 34}, // Den 201 (CT)
    {  550,  1088, 34}, // Den 202 (CT)
    {  811,  1048, 34}, // Den 203 (CT)
    {  817,   974, 34}, // Den 204 (CT)
    {  921,   996, 34}, // Den 205 (CT)
    {  889,  1048, 34}, // Den 206 (CT)
    {  993,   971, 34}, // Den 207 (CT)
    { 1082,   974, 34}, // Den 208 (CT)
    { 1566,  1015, 34}, // Den 209 (CT)
    {  642,  1067, 34}, // Den 210 (CT)
    {  675,  1197, 34}, // Den 211 (CT)
    {  761,  1086, 34}, // Den 212 (CT)
    { 1450,  1175, 34}, // Den 213 (CT)
    { 1628,  1162, 34}, // Den 214 (CT)
    {  969,   988, 34}, // Den 215 (CT)
    {  975,  1284, 34}, // Den 216 (CT)
    {  788,  1284, 34}, // Den 217 (CT)
    { 1480,  1121, 34}, // Den 218 (CT)
    { 1399,  1205, 34}, // Den 219 (CT)
    { 1423,  1102, 34}, // Den 220 (CT)
    { 1542,  1254, 34}, // Den 221 (CT)
    {  856,  1135, 35}, // Den 222 (CT)
    {  969,  1129, 35}, // Den 223 (CT)
    { 1581,   914, 36}, // Den 224 (CT)
    { 1462,   827, 36}, // Den 225 (CT)
    { 1426,   637, 36}, // Den 226 (CT)
    { 1310,   558, 36}, // Den 227 (CT)
    { 1263,   773, 36}, // Den 228 (CT)
    { 1328,   669, 36}, // Den 229 (CT)
    { 1221,   683, 36}, // Den 230 (CT)
    { 1379,   558, 36}, // Den 231 (CT)
    { 1539,   585, 36}, // Den 232 (CT)
    { 1444,   299, 37}, // Den 233 (CT)
    { 1474,   329, 37}, // Den 234 (CT)
    { 1402,   299, 37}, // Den 235 (CT)
    { 1325,   237, 38}, // Den 236 (CT)
    { 1604,  1058, 39}, // Den 237 (CT)
    { 1634,  1056, 39}, // Den 238 (CT)
    { 1720,  1075, 39}, // Den 239 (CT)
    { 1655,   999, 39}, // Den 240 (CT)
    { 1711,  1042, 39}, // Den 241 (CT)
    { 2207,   862, 40}, // Den 242 (CT)
    { 2201,   716, 40}, // Den 243 (CT)
    { 2525,   637, 40}, // Den 244 (CT)
    { 2579,   849, 40}, // Den 245 (CT)
    { 2579,   762, 40}, // Den 246 (CT)
    { 2599,   669, 40}, // Den 247 (CT)
    { 2460,   865, 40}, // Den 248 (CT)
    { 2632,   634, 40}, // Den 249 (CT)
    { 2466,   767, 40}, // Den 250 (CT)
    { 2489,   686, 40}, // Den 251 (CT)
    { 2665,   718, 40}, // Den 252 (CT)
    { 2614,   599, 40}, // Den 253 (CT)
    { 2442,   620, 40}, // Den 254 (CT)
    { 2602,   914, 40}, // Den 255 (CT)
    { 2293,   933, 41}, // Den 256 (CT)
    { 2320,   963, 41}, // Den 257 (CT)
    {  871,  1317, 42}, // Den 258 (CT)
    { 1254,  1418, 42}, // Den 259 (CT)
    { 1361,  1412, 42}, // Den 260 (CT)
    { 1468,  1412, 42}, // Den 261 (CT)
    { 1515,  1404, 42}, // Den 262 (CT)
    { 1598,  1646, 42}, // Den 263 (CT)
    { 1679,  1526, 42}, // Den 264 (CT)
    { 1432,  1641, 42}, // Den 265 (CT)
    { 1379,  1662, 42}, // Den 266 (CT)
    {  811,  1665, 42}, // Den 267 (CT)
    {  681,  1641, 42}, // Den 268 (CT)
    {  761,  1627, 42}, // Den 269 (CT)
    {  773,  1575, 42}, // Den 270 (CT)
    { 1462,  1578, 42}, // Den 271 (CT)
    { 1319,  1608, 42}, // Den 272 (CT)
    { 1290,  1456, 42}, // Den 273 (CT)
    { 1462,  1472, 42}, // Den 274 (CT)
    {  993,  1565, 43}, // Den 275 (CT)
};

inline constexpr int LOCATION_COUNT = 44;

inline constexpr const char* LOCATION_NAMES[44] = {
    "Axew's Eye", // 0
    "Bridge Field", // 1
    "Dappled Grove", // 2
    "Dusty Bowl", // 3
    "East Lake Axewell", // 4
    "Giant's Cap", // 5
    "Giant's Mirror", // 6
    "Giant's Seat", // 7
    "Hammerlocke Hills", // 8
    "Lake of Outrage", // 9
    "Motostoke Riverbank", // 10
    "North Lake Miloch", // 11
    "Rolling Fields", // 12
    "South Lake Miloch", // 13
    "Stony Wilderness", // 14
    "Watchtower Ruins", // 15
    "West Lake Axewell", // 16
    "Fields of Honor", // 17
    "Soothing Wetlands", // 18
    "Forest of Focus", // 19
    "Challenge Beach", // 20
    "Brawlers’ Cave", // 21
    "Challenge Road", // 22
    "Courageous Cavern", // 23
    "Loop Lagoon", // 24
    "Training Lowlands", // 25
    "Potbottom Desert", // 26
    "Workout Sea", // 27
    "Stepping-Stone Sea", // 28
    "Insular Sea", // 29
    "Honeycalm Sea", // 30
    "Honeycalm Island", // 31
    "Slippery Slope", // 32
    "Frostpoint Field", // 33
    "Giant’s Bed", // 34
    "Old Cemetery", // 35
    "Snowslide Slope", // 36
    "Path to the Peak", // 37
    "Crown Shrine", // 38
    "Giant’s Foot", // 39
    "Frigid Sea", // 40
    "Three-Point Pass", // 41
    "Ballimere Lake", // 42
    "Dyna Tree Hill", // 43
};

// Map image dimensions (pixel space for coordinates)
inline constexpr int MAP_IMG_W_WA  = 458;
inline constexpr int MAP_IMG_H_WA  = 1064;
inline constexpr int MAP_IMG_W_IOA = 1183;
inline constexpr int MAP_IMG_H_IOA = 1183;
inline constexpr int MAP_IMG_W_CT  = 1920;
inline constexpr int MAP_IMG_H_CT  = 2060;

} // namespace SwShDenLocations
