#!/usr/bin/env python3
"""
Fetch PLA spawner marker + slot JSONs from Lincoln-LM's repos and emit
include/pla/pla_markers.h with:
  - per-region constexpr Marker arrays (group_id, coords, ivs, slot range)
  - a flat SLOTS[] array of (species_name, weight, alpha) entries

Usage:
    python3 tools/convert_pla_spawners.py

Marker schema (JS-Finder):
    "0": {"coords":[x,y,z], "groupID":0, "ivs":3, "name":"lnd_ex_02"}

Slot schema (PLA-Live-Map):
    "lnd_ex_02": {
        "Dawn/None": {"Bidoof":100, "AlphaBidoof":2},
        ...
    }

We pick "Any Time/All Weather" if present, else the first time/weather bucket.
"""

import json
import os
import sys
import urllib.request

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
OUT_FILE = os.path.join(PROJECT_DIR, "include", "pla", "pla_markers.h")

MARKERS_BASE = "https://raw.githubusercontent.com/Lincoln-LM/JS-Finder/main/Resources/pla_spawners/jsons"
SLOTS_BASE   = "https://raw.githubusercontent.com/Lincoln-LM/PLA-Live-Map/main/static/resources"

REGIONS = [
    ("obsidianfieldlands", "OBSIDIAN_FIELDLANDS", "ObsidianFieldlands"),
    ("crimsonmirelands",   "CRIMSON_MIRELANDS",   "CrimsonMirelands"),
    ("cobaltcoastlands",   "COBALT_COASTLANDS",   "CobaltCoastlands"),
    ("coronethighlands",   "CORONET_HIGHLANDS",   "CoronetHighlands"),
    ("alabastericelands",  "ALABASTER_ICELANDS",  "AlabasterIcelands"),
]

# Map pixel dimensions (zoom 2, 8x8 tile grid of 256px = 2048px per side)
MAP_DIMS = {
    "obsidianfieldlands": (1024, 1024),
    "crimsonmirelands":   (1024, 1024),
    "cobaltcoastlands":   (1024, 1024),
    "coronethighlands":   (1024, 1024),
    "alabastericelands":  (1024, 1024),
}

# Exact world-space bounds per region.
# Derived from PLA-Live-Map static/js/universal.js:
#   maxBounds = unproject([0, 2048], 2) .. unproject([2048, 0], 2)
#   CRS.Simple scale(2) = 4  -> latlng extent [lng 0..512, lat -512..0]
#   convertCoords = [z*-0.5, x*0.5]  -> world x in [0, 1024], z in [0, 1024]
WORLD_BOUNDS = (0.0, 0.0, 1024.0, 1024.0)   # minX, minZ, maxX, maxZ

PREFERRED_TW_KEYS = ["Any Time/All Weather", "Any Time/None", "Dawn/None"]

def fetch(url):
    print(f"  fetching {url}")
    with urllib.request.urlopen(url, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))

def pick_time_weather(tw_map):
    for k in PREFERRED_TW_KEYS:
        if k in tw_map:
            return tw_map[k]
    # fall back to any key
    return next(iter(tw_map.values())) if tw_map else {}

def escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

def main():
    parts = [
        "#pragma once",
        "// Auto-generated by tools/convert_pla_spawners.py — do not edit manually.",
        "// Sources:",
        "//   markers: Lincoln-LM/JS-Finder Resources/pla_spawners/jsons/*.json",
        "//   slots:   Lincoln-LM/PLA-Live-Map static/resources/*.json",
        '#include "pla/pla_region.h"',
        "#include <cstdint>",
        "#include <cstddef>",
        "",
        "namespace PlaMarkers {",
        "",
        "struct SlotEntry {",
        "    const char* name;",
        "    uint16_t    weight;",
        "    bool        alpha;",
        "};",
        "",
        "struct Marker {",
        "    int32_t  groupId;",
        "    float    x, y, z;",
        "    uint8_t  ivs;",
        "    uint16_t slotOffset;",
        "    uint8_t  slotCount;",
        "    uint16_t slotTotal;",
        "};",
        "",
        "struct RegionBounds { float minX, minZ, maxX, maxZ; int mapImgW, mapImgH; };",
        "",
    ]

    flat_slots = []
    region_marker_blocks = []
    bounds_lines = []

    min_x_b, min_z_b, max_x_b, max_z_b = WORLD_BOUNDS
    for json_name, cpp_name, _ in REGIONS:
        markers = fetch(f"{MARKERS_BASE}/{json_name}.json")
        slot_tables = fetch(f"{SLOTS_BASE}/{json_name}.json")

        marker_lines = []
        for _, m in sorted(markers.items(), key=lambda kv: int(kv[0])):
            gid = int(m.get("groupID", 0))
            coords = m.get("coords", [0.0, 0.0, 0.0])
            x, y, z = float(coords[0]), float(coords[1]), float(coords[2])
            ivs = int(m.get("ivs", 0))
            name = m.get("name", "")

            slot_total = 0
            slot_offset = len(flat_slots)
            slot_count = 0
            tw_bucket = pick_time_weather(slot_tables.get(name, {}))
            for sp_name, weight in tw_bucket.items():
                w = int(weight)
                alpha = sp_name.startswith("Alpha")
                display = sp_name[5:] if alpha else sp_name
                flat_slots.append((display, w, alpha))
                slot_total += w
                slot_count += 1
            if slot_count > 255: slot_count = 255

            marker_lines.append(
                f"    {{ {gid}, {x:.2f}f, {y:.2f}f, {z:.2f}f, {ivs}, "
                f"{slot_offset}, {slot_count}, {slot_total} }},"
            )

        region_marker_blocks.append((cpp_name, marker_lines))

        w, h = MAP_DIMS[json_name]
        bounds_lines.append(
            f"    {{ {min_x_b:.2f}f, {min_z_b:.2f}f, "
            f"{max_x_b:.2f}f, {max_z_b:.2f}f, {w}, {h} }},"
        )

    # Emit SLOTS[]
    parts.append(f"inline constexpr SlotEntry SLOTS[] = {{")
    for name, w, alpha in flat_slots:
        parts.append(f'    {{ "{escape(name)}", {w}, {"true" if alpha else "false"} }},')
    parts.append("};")
    parts.append(f"inline constexpr size_t SLOTS_COUNT = {len(flat_slots)};")
    parts.append("")

    # Emit per-region marker arrays
    for cpp_name, lines in region_marker_blocks:
        parts.append(f"inline constexpr Marker {cpp_name}[] = {{")
        parts.extend(lines)
        parts.append("};")
        parts.append(f"inline constexpr size_t {cpp_name}_COUNT = {len(lines)};")
        parts.append("")

    parts.append("inline constexpr RegionBounds BOUNDS[5] = {")
    parts.extend(bounds_lines)
    parts.append("};")
    parts.append("")

    parts.append(
        "inline const Marker* getMarkers(PlaRegion r, size_t& count) {\n"
        "    switch (r) {\n"
        "        case PlaRegion::ObsidianFieldlands: count = OBSIDIAN_FIELDLANDS_COUNT; return OBSIDIAN_FIELDLANDS;\n"
        "        case PlaRegion::CrimsonMirelands:   count = CRIMSON_MIRELANDS_COUNT;   return CRIMSON_MIRELANDS;\n"
        "        case PlaRegion::CobaltCoastlands:   count = COBALT_COASTLANDS_COUNT;   return COBALT_COASTLANDS;\n"
        "        case PlaRegion::CoronetHighlands:   count = CORONET_HIGHLANDS_COUNT;   return CORONET_HIGHLANDS;\n"
        "        case PlaRegion::AlabasterIcelands:  count = ALABASTER_ICELANDS_COUNT;  return ALABASTER_ICELANDS;\n"
        "        default: count = 0; return nullptr;\n"
        "    }\n"
        "}\n"
    )
    parts.append(
        "inline int findMarker(int groupId, const Marker*& outMarker) {\n"
        "    for (int r = 0; r < (int)PlaRegion::Count; r++) {\n"
        "        size_t n; const Marker* ms = getMarkers((PlaRegion)r, n);\n"
        "        for (size_t i = 0; i < n; i++) {\n"
        "            if (ms[i].groupId == groupId) { outMarker = &ms[i]; return r; }\n"
        "        }\n"
        "    }\n"
        "    outMarker = nullptr;\n"
        "    return -1;\n"
        "}\n"
    )

    parts.append(
        "// Resolve a slot roll [0, slotTotal) to a SlotEntry for this marker.\n"
        "inline const SlotEntry* resolveSlot(const Marker& m, double slotRoll) {\n"
        "    if (m.slotCount == 0 || m.slotTotal == 0) return nullptr;\n"
        "    double acc = 0;\n"
        "    for (uint8_t i = 0; i < m.slotCount; i++) {\n"
        "        acc += SLOTS[m.slotOffset + i].weight;\n"
        "        if (slotRoll < acc) return &SLOTS[m.slotOffset + i];\n"
        "    }\n"
        "    return &SLOTS[m.slotOffset + m.slotCount - 1];\n"
        "}\n"
    )

    parts.append("} // namespace PlaMarkers")
    parts.append("")

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    total_slots = len(flat_slots)
    print(f"wrote {OUT_FILE} ({total_slots} slot entries)")

if __name__ == "__main__":
    sys.exit(main() or 0)
